version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  server:
    image: invitesvc:0.1.0
    command: ["-host", "0.0.0.0"]
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DSN=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
volumes:
  postgres:
